// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BattleShip.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260624105623_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Player_Data", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players_Data");
                });

            modelBuilder.Entity("ShipSizeScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number_ShipCells")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Player_DataId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Player_DataId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Player_DataId");

                    b.HasIndex("Player_DataId1");

                    b.ToTable("ShipSizeScore");
                });

            modelBuilder.Entity("ShipSizeScore", b =>
                {
                    b.HasOne("Player_Data", null)
                        .WithMany("HighScores_PvE")
                        .HasForeignKey("Player_DataId");

                    b.HasOne("Player_Data", null)
                        .WithMany("Highscores_PvP")
                        .HasForeignKey("Player_DataId1");
                });

            modelBuilder.Entity("Player_Data", b =>
                {
                    b.Navigation("HighScores_PvE");

                    b.Navigation("Highscores_PvP");
                });
#pragma warning restore 612, 618
        }
    }
}
