// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BattleShip.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aborted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AiDifficulty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BonusShotOnHit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DistanceMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GameEndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GameStartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MatchSetTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModePlayer")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("MatchPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DataPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasWon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IMatchID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatchDataId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberShipCells")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DataPlayerId");

                    b.HasIndex("MatchDataId");

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("Player_Data", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAI")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players_Data");
                });

            modelBuilder.Entity("MatchPlayer", b =>
                {
                    b.HasOne("Player_Data", "DataPlayer")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("DataPlayerId");

                    b.HasOne("Match", "MatchData")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("MatchDataId");

                    b.Navigation("DataPlayer");

                    b.Navigation("MatchData");
                });

            modelBuilder.Entity("Match", b =>
                {
                    b.Navigation("MatchPlayers");
                });

            modelBuilder.Entity("Player_Data", b =>
                {
                    b.Navigation("MatchPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
